# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bioformats2raw
description: Convert any Bioformats-compatible image to OME-Zarr format
keywords:
  - image formats
  - converter
  - OME-Zarr
components: []

input:
  - ch_meta:
      type: tuple
      description: |
        Channel of tuples containing a meta map, the input image, an 
        output path where the OME-Zarr should be created, and a memo directory
        where temporary files will be saved.
        Structure: [ val(meta), path(input_image), val(output_path), val(memo_directory) ]

output:
  - params:
      type: tuple
      description: |
        Same as the input tuple but replaces output paths with the OME-Zarr that 
        was created.
        Structure: [ val(meta), path(input_image), val(zarr_output_path) ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@krokicki"